### ISSUE TITLE
Missing slash commands

### ISSUE THREAD

**Issue by The-Noah** [BZFlag-Dev/bzflag.org#37]
The following slash commands appear to be missing from the docs:

- [ ] `/me`
- [ ] `/clientquery`
- [ ] `/listplugins`
- [ ] `/loadplugin`
- [ ] `/unloadplugin`
- [ ] `/poll set`
- [ ] `/say`

**Comment by blast007** [comment]
The /deregister command was removed before 2.4.0.  The /clientquery command isn't really useful, so I didn't include it.  And "/poll set" may just get removed since it's pretty useless and generally just results in abuse.

The /me and /say commands could probably be added.  And I guess the plugin commands could also be documented under Server Owner.

**Comment by The-Noah** [comment]
I'm working on moving the [Server Permissions](https://wiki.bzflag.org/Server_Permissions) over from the Wiki. Both `/poll set` and `/clientquery` have a permission associated with them so that's why I mentioned them.

**Comment by blast007** [comment]
Revision ebe6412 added /me, /say, /listplugins, /loadplugin and /unloadplugin.  The other two from this issue won't be documented.
